name       : haskell-cryptohash-sha256
version    : 0.11.101.0
release    : 6
source     :
    - https://hackage.haskell.org/package/cryptohash-sha256-0.11.101.0/cryptohash-sha256-0.11.101.0.tar.gz : 52756435dbea248e344fbcbcc5df5307f60dfacf337dfd11ae30f1c7a4da05dd
license    : BSD-3-Clause
component  : programming.haskell
summary    : A practical incremental and one-pass, pure API to the SHA-256 hash algorithm (including HMAC support) with performance close to the fastest implementations available in other languages.
description: |
    A practical incremental and one-pass, pure API to the SHA-256 hash algorithm (including HMAC support) with performance close to the fastest implementations available in other languages.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    sed -i "s|4.11|4.13|g" *.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
