name       : haskell-cryptohash-sha256
version    : 0.11.100.1
release    : 1
source     :
    - http://hackage.haskell.org/package/cryptohash-sha256-0.11.100.1/cryptohash-sha256-0.11.100.1.tar.gz : 57b02338e9648639335788b422dd4c744543cb0991347472e2e3628a33c2f5d6
license    : BSD-3-Clause
component  : programming
summary    : A practical incremental and one-pass, pure API to the SHA-256 hash algorithm (including HMAC support) with performance close to the fastest implementations available in other languages.
description: |
    A practical incremental and one-pass, pure API to the SHA-256 hash algorithm (including HMAC support) with performance close to the fastest implementations available in other languages.
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 cryptohash-sha256-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/cryptohash-sha256-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/cryptohash-sha256-$version/*.a
