name       : haskell-cryptohash-sha256
version    : 0.11.100.1
release    : 4
source     :
    - http://hackage.haskell.org/package/cryptohash-sha256-0.11.100.1/cryptohash-sha256-0.11.100.1.tar.gz : 57b02338e9648639335788b422dd4c744543cb0991347472e2e3628a33c2f5d6
license    : BSD-3-Clause
component  : programming.haskell
summary    : A practical incremental and one-pass, pure API to the SHA-256 hash algorithm
    (including HMAC support) with performance close to the fastest implementations
    available in other languages.
description: |
    A practical incremental and one-pass, pure API to the SHA-256 hash algorithm (including HMAC support) with performance close to the fastest implementations available in other languages.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
